-- Garantiza UTF-8 completo en la sesión y base de datos
SET NAMES utf8mb4;
ALTER DATABASE c_p_sunat CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE entity (
    ID_ENTITY BIGINT NOT NULL AUTO_INCREMENT,
    ID_DOCUMENT BIGINT NULL,
    ID_PHONE BIGINT NULL,
    ID_EMAIL BIGINT NULL,
    ID_ADDRESS BIGINT NULL,
    ID_USER BIGINT NULL,
    ID_ROLE INT NOT NULL,
    STATE TINYINT NOT NULL,
    DATE_RECORD DATETIME NOT NULL,
    PRIMARY KEY (ID_ENTITY)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE entity_natural (
    ID_NATURAL BIGINT NOT NULL AUTO_INCREMENT,
    ID_ENTITY BIGINT NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(70) NOT NULL,
    GENERO TINYINT NULL,
    DATE_BIRTH DATETIME NULL,
    STATE TINYINT NOT NULL,
    PRIMARY KEY (ID_NATURAL)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE entity_juridic (
    ID_JURIDIC BIGINT NOT NULL AUTO_INCREMENT,
    ID_ENTITY BIGINT NOT NULL,
    COMPANY_NAME VARCHAR(150) NULL, -- razon social
    TRADE_NAME VARCHAR(150) NULL, -- nombre comercial
    STATE TINYINT NOT NULL,
    PRIMARY KEY (ID_JURIDIC)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE entity_document (
    ID_DOCUMENT BIGINT NOT NULL AUTO_INCREMENT,
    ID_TYPE_DOCUMENT TINYINT NOT NULL,
    NUMBER_DOCUMENT VARCHAR(20) NOT NULL,
    STATE TINYINT NOT NULL,
    PRIMARY KEY (ID_DOCUMENT)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE type_document (
    ID_TYPE_DOCUMENT TINYINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(250) NOT NULL,
    LENGTH_DOCUMENT TINYINT NOT NULL,
    STATE TINYINT NOT NULL,
    PRIMARY KEY (ID_TYPE_DOCUMENT)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE entity_phone (
    ID_PHONE BIGINT NOT NULL AUTO_INCREMENT,
    NUMBER_PHONE VARCHAR(20) NULL,
    NUMBER_MOVIL VARCHAR(20) NULL,
    CODE_AREA VARCHAR(10) NULL,
    STATE TINYINT NOT NULL,
    PRIMARY KEY (ID_PHONE)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE entity_email (
    ID_EMAIL BIGINT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(100) NOT NULL,
    EMAIL_2 VARCHAR(100) NULL,
    STATE TINYINT NOT NULL,
    PRIMARY KEY (ID_EMAIL)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE entity_address (
    ID_ADDRESS BIGINT NOT NULL AUTO_INCREMENT,
    ADDRESS VARCHAR(250) NULL,
    CITY VARCHAR(100) NULL,
    DEPARTMENT VARCHAR(100) NULL,
    COUNTRY VARCHAR(100) NULL,
    UBIGEO VARCHAR(20) NULL,
    STATE TINYINT NOT NULL,
    PRIMARY KEY (ID_ADDRESS)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE entity_role (
    ID_ROLE INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR (100) NOT NULL,
    DESCRIPTION VARCHAR(250) NOT NULL,
    AMOUNT INT NULL,
    ID_COIN BIGINT NULL,
    STATE TINYINT NOT NULL,
    PRIMARY KEY (ID_ROLE)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE users (
    ID_USER BIGINT NOT NULL AUTO_INCREMENT,
    ID_ENTITY BIGINT NOT NULL,
    USER VARCHAR(100) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    DATE_RECORD DATETIME NOT NULL,
    STATE TINYINT NOT NULL,
    PRIMARY KEY (ID_USER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE project (
    ID_PROJECT BIGINT NOT NULL AUTO_INCREMENT,
    ID_USER BIGINT NULL,
    ID_NATURAL BIGINT NULL,
    ID_JURIDIC BIGINT NULL,
    NAME VARCHAR(250) NULL,
    AMOUNT DECIMAL(10,2) NULL,
    DATE_START DATETIME NOT NULL,
    DATE_END DATETIME NOT NULL,
    ID_COIN BIGINT NULL,
    STATE TINYINT NOT NULL,
    PRIMARY KEY (ID_PROJECT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE location (
    ID_LOCATION BIGINT NOT NULL AUTO_INCREMENT,
    ID_PROJECT BIGINT NOT NULL, 
    NAME VARCHAR(250) NOT NULL,
    ID_ADDRESS BIGINT NOT NULL,
    AMOUNT DECIMAL(10,2) NULL,
    DATE_START DATETIME NOT NULL,
    DATE_END DATETIME NOT NULL,
    ID_COIN BIGINT NULL,
    STATE TINYINT NOT NULL,
    PRIMARY KEY (ID_LOCATION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE voucher (
    ID_VOUCHER BIGINT NOT NULL AUTO_INCREMENT,
    TIPO VARCHAR(10) NOT NULL,
    SERIE VARCHAR(10) NOT NULL,
    N_SERIE VARCHAR(20) NOT NULL,
    RUC VARCHAR(20) NOT NULL,
    RS VARCHAR(250) NOT NULL,
    CONCEPT VARCHAR(250) NOT NULL,
    AMOUNT DECIMAL(10,2) NULL,
    E_C VARCHAR(250) NOT NULL,
    C_C VARCHAR(250) NOT NULL,
    CPE VARCHAR(250) NOT NULL,
    DATE_RECORD DATETIME NOT NULL,
    ID_COIN BIGINT NULL,
    STATE TINYINT NOT NULL,
    PRIMARY KEY (ID_VOUCHER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE transit (
    ID_TRANSIT BIGINT NOT NULL AUTO_INCREMENT,
    ID_VOUCHER BIGINT NOT NULL,
    ID_PROJECT BIGINT NOT NULL,
    ID_LOCATION BIGINT NOT NULL,
    ID_NATURAL BIGINT NOT NULL,
    STATE TINYINT NOT NULL,
    PRIMARY KEY (ID_TRANSIT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE coin (
    ID_COIN BIGINT NOT NULL AUTO_INCREMENT,
    ISO VARCHAR(10) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    SIMBOL VARCHAR(10) NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL,
    STATE TINYINT NOT NULL,
    PRIMARY KEY (ID_COIN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- Relaciones (al final)


ALTER TABLE entity 
    ADD CONSTRAINT entity_uno FOREIGN KEY (ID_DOCUMENT) REFERENCES entity_document(ID_DOCUMENT) 
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE entity
    ADD CONSTRAINT entity_dos FOREIGN KEY (ID_PHONE) REFERENCES entity_phone(ID_PHONE)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE entity
    ADD CONSTRAINT entity_tres FOREIGN KEY (ID_EMAIL) REFERENCES entity_email(ID_EMAIL)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE entity
    ADD CONSTRAINT entity_cuatro FOREIGN KEY (ID_ADDRESS) REFERENCES entity_address(ID_ADDRESS)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE entity
    ADD CONSTRAINT entity_cinco FOREIGN KEY (ID_ROLE) REFERENCES entity_role(ID_ROLE)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE entity_natural 
    ADD CONSTRAINT natural_entity FOREIGN KEY (ID_ENTITY) REFERENCES entity(ID_ENTITY)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE entity_juridic 
    ADD CONSTRAINT juridic_entity FOREIGN KEY (ID_ENTITY) REFERENCES entity(ID_ENTITY)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE entity_document
    ADD CONSTRAINT document_type FOREIGN KEY (ID_TYPE_DOCUMENT) REFERENCES type_document(ID_TYPE_DOCUMENT)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE users 
    ADD CONSTRAINT users_entity FOREIGN KEY (ID_ENTITY) REFERENCES entity(ID_ENTITY)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE project
    ADD CONSTRAINT project_user FOREIGN KEY (ID_USER) REFERENCES users(ID_USER)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE project
    ADD CONSTRAINT project_natural FOREIGN KEY (ID_NATURAL) REFERENCES entity_natural(ID_NATURAL)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE project
    ADD CONSTRAINT project_juridic FOREIGN KEY (ID_JURIDIC) REFERENCES entity_juridic(ID_JURIDIC)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE location 
    ADD CONSTRAINT location_project FOREIGN KEY (ID_PROJECT) REFERENCES project(ID_PROJECT)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- ALTER TABLE voucher
--     ADD CONSTRAINT entity FOREIGN KEY (ID_ENTITY) REFERENCES entity(ID_ENTITY)
--     ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE transit
    ADD CONSTRAINT transit_project FOREIGN KEY (ID_PROJECT) REFERENCES project(ID_PROJECT)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE transit
    ADD CONSTRAINT transit_location FOREIGN KEY (ID_LOCATION) REFERENCES location(ID_LOCATION)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE transit
    ADD CONSTRAINT transit_voucher FOREIGN KEY (ID_VOUCHER) REFERENCES voucher(ID_VOUCHER)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE transit
    ADD CONSTRAINT transit_natural FOREIGN KEY (ID_NATURAL) REFERENCES entity_natural(ID_NATURAL)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- Datos de inicio
INSERT INTO type_document (NAME, DESCRIPTION, LENGTH_DOCUMENT, STATE) VALUES
    ('DNI', 'Documento Nacional de Identidad', 8, 1),
    ('RUC', 'Registro Unico de Contribuyentes', 11, 1),
    ('PASAPORTE', 'Documento de viaje internacional', 12, 1);
INSERT INTO entity_role (NAME, DESCRIPTION, AMOUNT, ID_COIN, STATE) VALUES
    ('Admin', 'Administrador con todos los permisos', NULL, 19, 1),
    ('User', 'Usuario estandar', NULL, 19, 1),
    ('Jefe de proyecto', 'Administrador del proyecto', NULL, 19, 1),
    ('Colaborador', 'Colaborador del proyecto', NULL, 19, 1);
INSERT INTO entity_document (ID_TYPE_DOCUMENT, NUMBER_DOCUMENT, STATE) VALUES
    (1, '12345678', 1),
    (2, '20123456789', 1),
    (1, '45454567', 1),
    (1, '23234545', 1);
INSERT INTO entity_phone (NUMBER_PHONE, NUMBER_MOVIL, CODE_AREA, STATE) VALUES
    ('012345678', '999999999', '01', 1),
    ('098765432', '988888888', '01', 1),
    (NULL, '979797979', '01', 1),
    (NULL, '989867677', '01', 1);
INSERT INTO entity_address (ADDRESS, CITY, DEPARTMENT, COUNTRY, UBIGEO, STATE) VALUES
    ('Av. Siempre Viva 123', 'Springfield', 'Illinois', 'USA', '123456', 1),
    ('Calle Falsa 456', 'Shelbyville', 'Illinois', 'USA', '654321', 1);

INSERT INTO entity (ID_DOCUMENT, ID_PHONE, ID_EMAIL, ID_ADDRESS, ID_USER, ID_ROLE, STATE, DATE_RECORD) VALUES
    (1, 1, NULL, 1, 1, 1, 1, NOW()),
    (2, 2, NULL, 2, 1, 2, 1, NOW()),
    (3, 3, NULL, NULL, 1, 4, 1, NOW()),
    (4, 4, NULL, NULL, 1, 4, 1, NOW()); 
INSERT INTO entity_natural (ID_ENTITY, NAME, LAST_NAME, GENERO, DATE_BIRTH, STATE) VALUES
    (1, 'Arturo', 'Trejo Abarca', 1, '1990-05-15', 1),
    (3, 'Javier',  'Solis', 1, '2026-02-07', 1), 
    (4, 'Pedro', 'Infante', 1, '2026-02-07', 1); 
INSERT INTO entity_juridic (ID_ENTITY, COMPANY_NAME, TRADE_NAME, STATE) VALUES
    (2, 'Tech Solutions S.A.C.', 'TechSol', 1);

INSERT INTO users (ID_ENTITY, USER, PASSWORD_HASH, DATE_RECORD, STATE) VALUES
    (1, 'arturo', '$2b$10$/hsCLAGb99IqJ6/4KIJfLOqQZpIyOaCP02ibNbPKL391mH/yXrfJS', NOW(), 1),
    (2, 'techsol', '$2b$10$/hsCLAGb99IqJ6/4KIJfLOqQZpIyOaCP02ibNbPKL391mH/yXrfJS', NOW(), 1);


INSERT INTO project (ID_USER, ID_NATURAL, ID_JURIDIC, NAME, AMOUNT, DATE_START, DATE_END, ID_COIN, STATE) values
    (1, 1, 1, 'Proyecto Uno', 2000, '2026-02-01', '2026-03-14', 19, 1),
    (1, 1, 1, 'Proyecto Dos', 10000, '2026-02-01', '2026-03-14', 19, 1),
    (1, 3, 1, 'proyecto Tres', 5000, '2026-02-01', '2026-03-14', 19, 1);

INSERT INTO coin (ID_COIN, ISO, NAME, SIMBOL, COUNTRY, STATE) VALUES
    (1, 'ARS', 'Peso argentino', '$', 'Argentina', 1),
    (2, 'BOB', 'Boliviano', 'Bs.', 'Bolivia', 1),
    (3, 'BRL', 'Real brasileño', 'R$', 'Brasil', 1),
    (4, 'CAD', 'Dólar canadiense', '$', 'Canadá', 1),
    (5, 'CLP', 'Peso chileno', '$', 'Chile', 1),
    (6, 'COP', 'Peso colombiano', '$', 'Colombia', 1),
    (7, 'CRC', 'Colón costarricense', '₡', 'Costa Rica', 1),
    (8, 'CUP', 'Peso cubano', '$', 'Cuba', 1),
    (9, 'USD', 'Dólar estadounidense', '$', 'Ecuador', 1),
    (10, 'USD', 'Dólar estadounidense', '$', 'El Salvador', 1),
    (11, 'USD', 'Dólar estadounidense', '$', 'Estados Unidos', 1),
    (12, 'GTQ', 'Quetzal', 'Q', 'Guatemala', 1),
    (13, 'HTG', 'Gourde', 'G', 'Haití', 1),
    (14, 'HNL', 'Lempira', 'L', 'Honduras', 1),
    (15, 'MXN', 'Peso mexicano', '$', 'México', 1),
    (16, 'NIO', 'Córdoba', 'C$', 'Nicaragua', 1),
    (17, 'PAB', 'Balboa', 'B/. / $', 'Panamá', 1),
    (18, 'PYG', 'Guaraní', '₲', 'Paraguay', 1),
    (19, 'PEN', 'Sol', 'S/', 'Perú', 1),
    (20, 'DOP', 'Peso dominicano', 'RD$', 'Rep. Dominicana', 1),
    (21, 'UYU', 'Peso uruguayo', '$', 'Uruguay', 1),
    (22, 'VES', 'Bolívar Soberano', 'Bs.S', 'Venezuela', 1),
	(23, 'EUR', 'Euro',	'€', 'España', 1);

-- Datos iniciales para locations (requiere projects, addresses y coins creados)
INSERT INTO location (ID_PROJECT, NAME, ID_ADDRESS, AMOUNT, DATE_START, DATE_END, ID_COIN, STATE) VALUES
    (1, 'Sede Lima',   1, 1200.00, '2026-02-01', '2026-02-28', 19, 1),
    (1, 'Sede Callao', 2,  800.00, '2026-02-10', '2026-03-01', 19, 1),
    (2, 'Almacén Surco', 1, 1500.00, '2026-02-05', '2026-03-10', 19, 1);
-- Vistas


-- Procedimientos almacenados


